from . import admin
from . import config
from . import custom_test
from . import db
from . import index
from . import login
from . import problems
from . import problems_manage
from . import reedis
from . import register
from . import static
from . import submissions
from . import users
